# Generated by Django 5.2.5 on 2025-08-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_detail_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='category_id',
            new_name='category',
        ),
    ]
