# Generated by Django 5.2.5 on 2025-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
